// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:71130469-550d-4a76-a4c9-9fd704c79713",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_pvZViZmhP",
    "aws_user_pools_web_client_id": "518qb5va9p5a98vva6hbnau32j",
    "aws_appsync_graphqlEndpoint": "https://rfhretmprfhfxgfrirmt7uupmm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4it3ywqnqrguhkokjlre3qnuyu",
    "aws_user_files_s3_bucket": "foodmanagementd55f6622a99f4e8d855baba9a6b1a41a",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
